create user sqooptest identified by 12345 default tablespace users;
alter user sqooptest quota unlimited on users;
grant create session to sqooptest;
grant create procedure to sqooptest;
grant alter session to sqooptest;
grant select on v_$instance to sqooptest;
grant select on dba_tables to sqooptest;
grant select on dba_tab_columns to sqooptest;
grant select on dba_objects to sqooptest;
grant select on dba_extents to sqooptest;
grant select on dba_segments to sqooptest;
grant select on v_$database to sqooptest;
grant select on v_$parameter to sqooptest;
grant select on v_$session to sqooptest;
grant select on v_$sql to sqooptest;
grant create table to sqooptest;
grant select on dba_tab_partitions to sqooptest;
grant select on dba_tab_subpartitions to sqooptest;
grant select on dba_indexes to sqooptest;
grant select on dba_ind_columns to sqooptest;
grant select any table to sqooptest;
grant create any table to sqooptest;
grant insert any table to sqooptest;
grant alter any table to sqooptest;

create user sqooptest2 identified by ABCDEF default tablespace users;
alter user sqooptest2 quota unlimited on users;
grant create session to sqooptest2;
grant create procedure to sqooptest2;
grant alter session to sqooptest2;
grant select on v_$instance to sqooptest2;
grant select on dba_tables to sqooptest2;
grant select on dba_tab_columns to sqooptest2;
grant select on dba_objects to sqooptest2;
grant select on dba_extents to sqooptest2;
grant select on dba_segments to sqooptest2;
grant select on v_$database to sqooptest2;
grant select on v_$parameter to sqooptest2;
grant select on v_$session to sqooptest2;
grant select on v_$sql to sqooptest2;
grant create table to sqooptest2;
grant select on dba_tab_partitions to sqooptest2;
grant select on dba_tab_subpartitions to sqooptest2;
grant select on dba_indexes to sqooptest2;
grant select on dba_ind_columns to sqooptest2;
grant select any table to sqooptest2;
grant create any table to sqooptest2;
grant insert any table to sqooptest2;
grant alter any table to sqooptest2;
